name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy-staging-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: 🛠️ Checkout code
        uses: actions/checkout@v3

      - name: 🌐 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: 📦 Install dependencies
        run: |
          npm install --no-fund
          npm audit fix --force || true

      - name: 🔧 Create .env file
        run: |
          cat > .env << EOL
          NEXT_PUBLIC_APP_URL=${{ secrets.STAGING_APP_URL }}
          NEXT_PUBLIC_ENVIRONMENT=staging
          SMTP_HOST=${{ secrets.SMTP_HOST }}
          SMTP_PORT=${{ secrets.SMTP_PORT }}
          SMTP_USER=${{ secrets.SMTP_USER }}
          SMTP_PASS=${{ secrets.SMTP_PASS }}
          SMTP_FROM="${{ secrets.SMTP_FROM }}"
          CONTACT_EMAIL="${{ secrets.CONTACT_EMAIL }}"
          FTP_SERVER=${{ secrets.STAGING_FTP_SERVER }}
          FTP_USERNAME=${{ secrets.STAGING_FTP_USERNAME }}
          FTP_PASSWORD=${{ secrets.STAGING_FTP_PASSWORD }}
          EOL

      - name: 🚧 Aktiviere Wartungsmodus
        uses: appleboy/ssh-action@v1.0.3
        continue-on-error: true
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd staging.callflows.de/
            touch .maintenance

      - name: 🗄️ Backup
        uses: appleboy/ssh-action@v1.0.3
        continue-on-error: true
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd staging.callflows.de/
            timestamp=$(date +%Y%m%d_%H%M%S)
            mkdir -p backups
            tar -czf backups/backup-${timestamp}.tar.gz ./out
            mysqldump -h ${{ secrets.STAGING_DB_HOST }} -u ${{ secrets.STAGING_DB_USER }} -p${{ secrets.STAGING_DB_PASS }} ${{ secrets.STAGING_DB_NAME }} > backups/db-backup-${timestamp}.sql || true

      - name: 🏗️ Build
        run: npm run build

      - name: 🧹 Empty remote directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd staging.callflows.de/
            rm -rf * .env
            mkdir -p logs
            chmod 755 logs

      - name: 📤 Deploy to Staging
        env:
          FTP_SERVER: ${{ secrets.STAGING_FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.STAGING_FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.STAGING_FTP_PASSWORD }}
        run: |
          npm install ftp-deploy
          node scripts/deploy.js

      - name: 🧹 Clean npm cache
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: 🟢 Deaktiviere Wartungsmodus
        if: always()
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd staging.callflows.de/
            rm -f .maintenance

      - name: 📦 Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
