name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy-staging-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: 🛠️ Checkout code
        uses: actions/checkout@v3

      - name: 🌐 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: 📦 Install dependencies
        run: |
          npm install --no-fund
          npm audit fix --force || true

      - name: 🔧 Create .env file
        run: |
          echo "NEXT_PUBLIC_ENVIRONMENT=staging" >> .env
          echo "DB_HOST=${{ secrets.STAGING_DB_HOST }}" >> .env
          echo "DB_USER=${{ secrets.STAGING_DB_USER }}" >> .env
          echo "DB_PASS=${{ secrets.STAGING_DB_PASS }}" >> .env
          echo "DB_NAME=${{ secrets.STAGING_DB_NAME }}" >> .env

      - name: 🚧 Aktiviere Wartungsmodus
        uses: appleboy/ssh-action@v1.0.3
        continue-on-error: true
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd staging.callflows.de
            touch .maintenance

      - name: 🗄️ Backup
        uses: appleboy/ssh-action@v1.0.3
        continue-on-error: true
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd staging.callflows.de
            timestamp=$(date +%Y%m%d_%H%M%S)
            mkdir -p backups
            tar -czf backups/backup-${timestamp}.tar.gz ./out
            mysqldump -h ${{ secrets.STAGING_DB_HOST }} -u ${{ secrets.STAGING_DB_USER }} -p${{ secrets.STAGING_DB_PASS }} ${{ secrets.STAGING_DB_NAME }} > backups/db-backup-${timestamp}.sql || true

      - name: 🏗️ Build
        run: npm run build

      - name: 🧹 Empty remote directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd staging.callflows.de/
            rm -rf * .env

      - name: 📤 Deploy to Staging
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.STAGING_FTP_SERVER }}
          username: ${{ secrets.STAGING_FTP_USERNAME }}
          password: ${{ secrets.STAGING_FTP_PASSWORD }}
          local_path: './out/*'
          remote_path: '/staging.callflows.de/'
          sftpArgs: '-o StrictHostKeyChecking=no'
          sftp_only: true
          port: 22

      - name: 🧹 Clean npm cache
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: 🟢 Deaktiviere Wartungsmodus
        if: always()
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd staging.callflows.de
            rm -f .maintenance

      - name: 📦 Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
