name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy-staging-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: 🛠️ Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          show-progress: false

      - name: 🌐 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: 📦 Install dependencies
        run: |
          npm ci --no-fund --no-audit --prefer-offline --progress=false

      - name: 🔧 Create .env file
        run: |
          cat > .env << EOL
          NEXT_PUBLIC_APP_URL=${{ secrets.STAGING_APP_URL }}
          NEXT_PUBLIC_ENVIRONMENT=staging
          SMTP_HOST=${{ secrets.SMTP_HOST }}
          SMTP_PORT=${{ secrets.SMTP_PORT }}
          SMTP_USER=${{ secrets.SMTP_USER }}
          SMTP_PASS=${{ secrets.SMTP_PASS }}
          SMTP_FROM=${{ secrets.SMTP_FROM }}
          CONTACT_EMAIL=${{ secrets.CONTACT_EMAIL }}
          FTP_SERVER=${{ secrets.STAGING_FTP_SERVER }}
          FTP_USERNAME=${{ secrets.STAGING_FTP_USERNAME }}
          FTP_PASSWORD=${{ secrets.STAGING_FTP_PASSWORD }}
          ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}
          CUSTOMER_USERNAME=${{ secrets.CUSTOMER_USERNAME }}
          CUSTOMER_PASSWORD=${{ secrets.CUSTOMER_PASSWORD }}
          EOL

      - name: 🚧 Aktiviere Wartungsmodus
        uses: appleboy/ssh-action@v1.0.3
        continue-on-error: true
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd staging.callflows.de/
            touch .maintenance

      - name: 🗄️ Backup
        uses: appleboy/ssh-action@v1.0.3
        continue-on-error: true
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd staging.callflows.de/
            timestamp=$(date +%Y%m%d_%H%M%S)
            mkdir -p backups
            # Backup aller Dateien außer Backups und Logs
            tar -czf backups/backup-${timestamp}.tar.gz --exclude='backups' --exclude='logs' --exclude='.maintenance' . || true
            # Nur die letzten 5 Backups behalten
            ls -t backups/backup-*.tar.gz | tail -n +6 | xargs rm -f || true

      - name: 🧹 Empty remote directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd staging.callflows.de/
            rm -rf * .env

      - name: 🏗️ Build
        run: npm run build

      - name: 📤 Deploy to Staging
        env:
          FTP_SERVER: ${{ secrets.STAGING_FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.STAGING_FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.STAGING_FTP_PASSWORD }}
          NODE_ENV: staging
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: |
          node scripts/ci-fast-deploy.js

      - name: 🧹 Clean temporary files
        run: |
          rm -rf out
          rm -f .deploy-checksums.json

      - name: 🟢 Deaktiviere Wartungsmodus
        if: always()
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd staging.callflows.de/
            rm -f .maintenance
